[build]
base = "/"
publish = "site/"
command = "zensical build --clean --strict"

[build.environment]
    PYTHON_VERSION = "3.14"
    NODE_VERSION = "24"
    CI = "true"
    DISABLE_OPENCOLLECTIVE = "true"
    OPENCOLLECTIVE_HIDE = "true"
