# ----------------------------------------------------------------------------
# Global options section
# ----------------------------------------------------------------------------

[project]
site_name = "Pi-hole documentation"
site_url = "https://docs.pi-hole.net/"
site_description = "A black hole for Internet advertisements"
site_author = "Pi-hole Team"
repo_url = "https://github.com/pi-hole/pi-hole"

edit_uri = "../docs/blob/master/docs/"

docs_dir = "docs"

# This is overwritten by orverrides/partials/copyright.html
# see https://zensical.org/docs/customization/?h=over#overriding-partials
copyright = ""

extra_css = ["extra.css"]
#extra_javascript = ["assets/javascript/extra.js"]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]

# change this to "classic" to use the traditional Material for MkDocs look.
variant = "modern"

custom_dir = "overrides"
favicon = "images/favicon.ico"
logo = "images/logo.svg"
language = "en"

# Zensical provides a number of feature toggles that change the behavior
# of the documentation site.
features = [
    #"announce.dismiss",
    "content.action.edit",
    #"content.action.view",
    #"content.code.annotate",
    "content.code.copy",
    #"content.code.select",
    #"content.footnote.tooltips",
    "content.tabs.link",
    #"content.tooltips",
    # "header.autohide",
    # "navigation.expand",
    #"navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    #"navigation.instant.progress",
    #"navigation.path",
    #"navigation.prune",
    #"navigation.sections",
    #"navigation.tabs",
    #"navigation.tabs.sticky",
    "navigation.top",
    #"navigation.tracking",
    "search.highlight",
    # "toc.follow",
    #"toc.integrate",
]

# Palette toggle for light mode
[[project.theme.palette]]
scheme = "default"
media = "(prefers-color-scheme: light)"
palette.primary = "indigo"
palette.accent = "indigo"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
scheme = "slate"
media = "(prefers-color-scheme: dark)"
palette.primary = "indigo"
palette.accent = "indigo"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Source Sans Pro"
code = "Roboto Mono"

# ----------------------------------------------------------------------------
# Section for markdown extensions
# ----------------------------------------------------------------------------

[project.markdown_extensions.abbr]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.toc]
permalink = "true"
permalink_title = "Anchor link to this section"

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.snippets]
auto_append = ["abbreviations.md"]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = "true"

[project.markdown_extensions.pymdownx.tilde]

# ----------------------------------------------------------------------------
# Section for configuring extra options
# ----------------------------------------------------------------------------

[[project.extra.social]]
icon = "fontawesome/solid/earth-americas"
link = "https://pi-hole.net/"
name = "Website"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/pi-hole"
name = "GitHub"

# ----------------------------------------------------------------------------
# Navigation section
# ----------------------------------------------------------------------------

# nav = [
#   { "Get started" = "index.md" },
#   { "Markdown in 5min" = "markdown.md" },
# ]
